title: 'LLMアプリ実践 - Gemini編'
summary: 'Geminiを使ったLLMアプリの実践的な開発方法を学ぶ'
topics: ['Gemini', 'LLMアプリ', '実践']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01-preparation
  - example2
  - get-gemini-api-key
